clear; clc;
filename = 'N1_32n1_1920N2_0n2_0N3_0n3_0z_95NAll_61440crosslinkfinal.ord';
outputname = ['pdms_' 'DFS_' filename(1:end-4) '.data'];
ranDeflection = 0.2;
data = readmatrix(filename,"FileType","text");
[Natom, column] = size(data);
Tatom = 1;
group = (column - 5)/2;
xyz = data(:,1:3);
k = 4; %距离放大系数
% ===== 随机球面扰动（半径 r）=====
r = 0.2;   % 你可以改，要求 r < 1

% 生成随机方向（高斯分布）
rand_vec = randn(Natom, 3);

% 归一化到单位球面
norms = sqrt(sum(rand_vec.^2, 2));
unit_vec = rand_vec ./ norms;

% 乘以半径 r，得到球面上的点
displacement = r * unit_vec;

% 更新坐标
xyz = xyz + displacement;

xyz = k * xyz;
xlo = 0; % min(xyz(:,1));
xhi = k * 300; % max(xyz(:,1));
ylo = 0; % min(xyz(:,2));
yhi = k * 32; % max(xyz(:,2));
zlo = min(xyz(:,3));
zhi = max(xyz(:,3));
atomID = 1:Natom;
atomID = atomID(:);
atomType = ones([Natom,1]);
atomCharge = zeros([Natom,1]);
molemerID = data(:,end);
Atoms = [atomID, atomType, atomType, atomCharge, xyz];

% 获取bond信息
bondList = [];
bondID = 1;
for i = 1:Natom
    % 官能团连接列起始位置
    conn_start = 5 + group;

    for g = 1:group
        j = data(i, conn_start + g - 1);

        if j > 0 && j > i   % 防止重复
            bondList(end+1,:) = [bondID, 1, i, j];
            bondID = bondID + 1;
        end
    end
end
Nbond = size(bondList,1);
adj = cell(Natom,1);
for b = 1:Nbond
    i = bondList(b,3);
    j = bondList(b,4);

    adj{i} = [adj{i}, j];
    adj{j} = [adj{j}, i];
end

% 获取angle信息
adj = cell(Natom,1);

for b = 1:size(bondList,1)
    i = bondList(b,3);
    j = bondList(b,4);

    adj{i} = [adj{i}, j];
    adj{j} = [adj{j}, i];
end

paths2 = dfs_paths(adj, 2);

angleSet = [];

for i = 1:length(paths2)
    p = paths2{i};

    if length(p) == 3
        % 去重：保证 i < k
        if p(1) < p(3)
            angleSet(end+1,:) = p;
        end
    end
end

% 去重（防止不同DFS路径重复）
angleSet = unique(angleSet, 'rows');

% 转换为LAMMPS格式
angleList = [(1:size(angleSet,1))', ones(size(angleSet,1),1), angleSet];

% 获取dihedral信息
paths3 = dfs_paths(adj, 3);

dihedralSet = [];

for i = 1:length(paths3)
    p = paths3{i};

    if length(p) == 4
        % 去重：比较正反序，保留字典序小的
        p_rev = fliplr(p);

        if lexicographically_smaller(p, p_rev)
            dihedralSet(end+1,:) = p;
        end
    end
end

% 去重
dihedralSet = unique(dihedralSet, 'rows');

dihedralList = [(1:size(dihedralSet,1))', ones(size(dihedralSet,1),1), dihedralSet];

% ===== 加上ID和type =====
Ndihedral = size(dihedralList,1);
Nangle = size(angleList,1);

% 生成文件头
writelines('# Generated by MATLAB',outputname)
writelines(sprintf('%d atom types',Tatom),outputname,'WriteMode','append')
writelines(sprintf('%d atoms',Natom),outputname,'WriteMode','append')
writelines(sprintf('%d bond types',1),outputname,'WriteMode','append')
writelines(sprintf('%d bonds', Nbond),outputname,'WriteMode','append')
writelines(sprintf('%d angle types',1),outputname,'WriteMode','append')
writelines(sprintf('%d angles', Nangle),outputname,'WriteMode','append')
writelines(sprintf('%d dihedral types',1),outputname,'WriteMode','append')
writelines(sprintf('%d dihedrals\n', Ndihedral),outputname,'WriteMode','append')

% 写入box信息
xbox = sprintf('%.4f %.4f xlo xhi',xlo, xhi);
writelines(xbox,outputname,'WriteMode','append')
ybox = sprintf('%.4f %.4f ylo yhi',ylo, yhi);
writelines(ybox,outputname,'WriteMode','append')
zbox = sprintf('%.4f %.4f zlo zhi\n',zlo, zhi);
writelines(zbox,outputname,'WriteMode','append')

% 写入Masses
writelines('Masses',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writelines('1 72',outputname,'WriteMode','append')

% 写入Atoms
writelines('',outputname,'WriteMode','append')
writelines('Atoms  # full',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writematrix(Atoms,outputname,"WriteMode","append",'FileType','text','Delimiter',' ')

% 写入Bonds
writelines('',outputname,'WriteMode','append')
writelines('Bonds',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writematrix(bondList,outputname,"WriteMode","append",'FileType','text','Delimiter',' ')

% 写入Angles
writelines('',outputname,'WriteMode','append')
writelines('Angles',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writematrix(angleList,outputname,"WriteMode","append",'FileType','text','Delimiter',' ')

% 写入Dihedrals
writelines('',outputname,'WriteMode','append')
writelines('Dihedrals',outputname,'WriteMode','append')
writelines('',outputname,'WriteMode','append')
writematrix(dihedralList,outputname,"WriteMode","append",'FileType','text','Delimiter',' ')

function paths = dfs_paths(adj, maxLen)
    N = length(adj);
    paths = {};

    for start = 1:N
        stack = {[start]};

        while ~isempty(stack)
            path = stack{end};
            stack(end) = [];

            if length(path) >= 2
                paths{end+1} = path;
            end

            if length(path) == maxLen + 1
                continue;
            end

            last = path(end);

            for nei = adj{last}
                if ~ismember(nei, path)   % simple path
                    stack{end+1} = [path, nei];
                end
            end
        end
    end
end

function flag = lexicographically_smaller(a, b)
    for i = 1:length(a)
        if a(i) < b(i)
            flag = true;
            return;
        elseif a(i) > b(i)
            flag = false;
            return;
        end
    end
    flag = false;
end